"""""""""""""""" Ajustes generales de vim """"""""""""""""""""""""""
" Vi compatible

syntax on
set encoding=utf-8
set background=dark
set shiftwidth=4
set mouse+=a 
set expandtab
set tabstop=4
set cursorline
set incsearch
set hlsearch
set confirm 
set number
set ff=unix
set paste
set rnu

" store backup, undo, and swap files in temp directory
" set directory=$HOME/temp//
set backupdir=$HOME/temp//
set undodir=$HOME/temp//

"""""""""""" Final de ajustes generales"""""""""""""""




