"""""""""""""""" Ajustes generales de vim """"""""""""""""""""""""""
" Vi compatible

syntax on
set encoding=utf-8
set background=dark
set shiftwidth=4
set mouse+=a 
set expandtab
set tabstop=4
set cursorline
set incsearch
set hlsearch
set confirm 
set number
set ff=unix
set paste
set rnu

" Almacenar archivos de copia de seguridad, deshacer e intercambiar en el directorio temporal
set backupdir=$HOME/temp//
set undodir=$HOME/temp//

"""""""""""" Final de ajustes generales"""""""""""""""




